language: node_js

cache: yarn

node_js:
  - 8
  - 10

before_install:
  - npm i -g yarn

script:
  - yarn build
  - yarn test

notifications:
  slack:
    secure: iSLAn6hs4VTvo07Vpsj2RoWrqr4sNYALKk3lqJepeo2o9L454fAkh9m3OBEzFWT5g7p493lTsr04t0soAwp1nXo8+OkhFYPHuofz85OpMdSb9dNI9m2fOdTfSdwmxNBlCgicG0ZLNoJBMhJc5hzShNXE86mjE64ATwMh+WbmyO+8xmaHG9P1CmgEn66t6LLqvJdyV2gA3GUGC418MR0dp4B7S2SrP21v4L5SfFJmDAaRbPh/6gGop+kUsD05EpIU9O0glSaLZX2g251kqG0Rvqfb1X2RruJZQ2UoKJX/FxEUl5NV5xA1pQbI9SAQDLymXpm3fMg50EMyUs7+x+5vVqgUZpUvMzx5NcO1FcymVWtmWWFN/b3ojtb2X6dsufr3Ao27y2DZx/Vm5FXRxqsI+5fSGsHjt4Z/6y0O30IZasJvDIztXTDKNBSKnjEVaSor3YzfTFBPiyPptkJfMlMTYKmGCMn3QYm8UZycFVpHtExy3TnqcV57imEcxLCs3f7oUQZc4sR+l3AI9VK6j2L1AAAY1UNL5785+AjVKvuKYT+E08sAlPzT/WWvo9As7ybLIW5NmoysUVFWUAosjqF7DI1wZjpH3gHqEOMj4BT+aSD27hDIx9yJDLxWMB5mD4guAa3LQVm9rdyJ9xfPZ2u9PHBPzQK28BlmSCl3XrzreL4=

env:
  global:
    - secure: vy4moGLO3CjFw/eOoeMmG6DDA6dN/UeeT1Rfm3tVd6Z2U5ueRL+E6w0s4I+jDNJRxCekGeD01IMCS38hGpVGt/+Vs4NZHBUH1zHDIzQCAIf4ONkltjUQeq+CTPyU78E2JqXTXjn37Im48wsuWYSmtj5nq1s3+5ELoETHCWMZuRzBqG3SjnrQgydVVdG/wCUzk9gjgghtr3PuyVkNdg2nF6PJmw2bbDYud2D50qElHbkvbjBzmB+RNTukLsb2Bi++2yT5aMT091Nxg8vkNgDVcFOpobFf1+X4pTAoHsy9iinPOmD9JW9z77IQObXi4+R2PVgUaKprjJXHEu6nGUICVWEaMIUXUHWzDaCtR2Hd4YIV6Emufpi3gzP63DDm/zggzE2Gy5eehoaYE3/ozX2SIT1Bi0Ybrg+VY0RQHROcoLKFJo60Q7PuSLkUyhrR7E6/kxSRzKxfEJNU0J1ZeJj1tUf4KUDqi5lC1VD86EU0mPVohHahA/cxkkNGTUn9hXUAmHqGkfurHw7k76sALiB+fSgUwrCMocRnQFrmWUclXL2P4UdyB15mO9xBH1EDRTz+ZefMyTHuQOTyBlXfB0k/KtGLz7XF3TpRIAY8uKStCWJYXg5hFWpY6+MxjNNivsTBd4aPaTDnuKxLQTFaY2xeDrZW073ClsUlwchSisfymOE=
    - secure: R/P8HY54nhGFK/ye1+1WCH82s6d/xhO3LAJZS0pw1h0UZ72sCPBp7BQJtT3Pv1+6xX2kK5asb4YXbH8YyRIN/XmiKbMJToQMVYTsNU19ttKS3cn7bQbOkTZgHYXBLZbECj3rSc0kmNgp1Gv9SwpMbox9DR6ycO+yagVcwbJyL//g6ViQ75aThuiIX1mygAoc8F7aLe+ZbHRh1CcxkdAsR6ePA3DjPTQQTcUFEnkWmfDhgBp9XHeFnCbhbqyiIdaOgRiUZGEPf+dlK9ubrifS22LzV7mr185NRVchu9/dC5RsgjolU8kaKE1j0E2ZMGMxxArbNf1zGjHFcwOVm7mkcJ96QjXKdrBjZn0nsfPAgK2JXRb8gDY632UBlJSPEN+pEPdLWF1X5QNvYny0mS27Dn0DSquposOczpzCDFixx4dxD0Zirrp5vbBf5m3STSitKG9FE/IFrV/W4HhlCkqX+ByLsBJPaejyTq3T2HxBNrLGryfWWwOCBYDVi1B4ETpEBByphJHM4WwQZfkSwBQHJeLoVtR1Fs6zwe5KBDyPoxAWYFo3ddjg/QLX3SFpO7XgosT+hw8mNwjY+opmEpeFF+MF02khSOIi0EJGuAwaqxQjkBd5bFCf2kF0NPoCVOxl4L4tjUrHec+DSSKLBvcfQeS3Mhlswf5LEQkFEH5ckBw=
    - secure: go2iGdBeKjfbaxmT8cesl9LywLCGGTJAScJvcghXpdMiY8hn4h9MhACKiqPzGbVrHfvnBnQFkAiahoBxA0LhCw5XmuiWdhFLvuqFjKNBeiIzjwv+0G84iJBce7aS9DBq6r9Ju8Ssceb6Zvx4pEa/YAxrjkjDpJAxExorGCsXP/FY/R4WWUF2jhNq183Gebe2s0VnceFT7nypg6CWc/kH6lfrlL+k0i9ou01UXfRvtpfaLUfrLrlmJKV8f1c0o4UzXjWrBIfafJsSVzrdtQprqonLhc2aV+Uv/Lcl0omJi+vcQA0k9EAV3iKs4u/IEwr90eG34VbM9h/UVD/qaSlMBTqr3cvQ05gzFerItfcg23/FQyobpEwkgAIuUrIgD8xEceRVIj+9+Qxd2FYEMSEGYC54plIoa5DD/l0SRD6KzCCYylWSNlNs7Lv8S3vNNNciKv4XqdG70wB2OaWF53dt/rf1IoS5ILMuVvhEaLkARsfjWenSuX4DGODTLWysf3JVrOwgmlQFnubl4ulflb/4hZ8OYSaIhy5ofxNH5YsVu+X8/HtcUqSMgf52k3z1UladOa0/hnvjSRbn9hhHb+5qThxNam9KLKcR8vEFZGyoiHRS4cRPc3rrsK5WBpUa4PaMwjt+/Vmz+eZovjJoi07RKazPj3+4BuOdAIaqKlXrjcg=
    - export GIT_AUTHOR_NAME="EndemolShineGroupUser"
    - export GIT_AUTHOR_EMAIL="tech@endemolshine.com"
    - export GIT_COMMITTER_NAME="EndemolShineGroupUser"
    - export GIT_COMMITTER_EMAIL="tech@endemolshine.com"

jobs:
  include:
    - stage: coverage
      if: type != pull_request
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      after_success:
        - yarn global add codecov
        - codecov
    - stage: release
      if: branch = master AND type != pull_request
      after_success:
        - yarn semantic-release
        - git clone https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git fetch --all
        - git merge origin/master
        - git push
